// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MiniaspFeedbackAPI.Models;
using System;

namespace MiniaspFeedbackAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniaspFeedbackAPI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Experience");

                    b.Property<string>("HowToWork");

                    b.Property<string>("Name");

                    b.Property<string>("Suggestion");

                    b.Property<string>("TicketID")
                        .IsRequired();

                    b.Property<string>("WantToLearn");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("MiniaspFeedbackAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Tel");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MiniaspFeedbackAPI.Models.Utoken", b =>
                {
                    b.Property<string>("UtokenId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IP");

                    b.Property<DateTime>("LastInTime");

                    b.Property<DateTime>("UTokenTimeOut");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("UtokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Utoken");
                });

            modelBuilder.Entity("MiniaspFeedbackAPI.Models.Utoken", b =>
                {
                    b.HasOne("MiniaspFeedbackAPI.Models.User", "User")
                        .WithMany("Utokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
